<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Authors>Angelo Pirola</Authors>
        <Company>Angelo Pirola</Company>
        <Product>AppEngine</Product>
        <Title>AppEngine</Title>
        <Description>A lightweight development engine for .NET web applications, designed to simplify and provide essential tools for developing web apps.</Description>
        <PackageId>AppEngine</PackageId>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/AngeloDotNet/AppEngine</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>
</Project>