<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Authors>Angelo Pirola</Authors>
        <Company>Angelo Pirola</Company>
        <Product>AppEngine.Tools</Product>
        <Title>AppEngine Tools</Title>
        <Description>A lightweight development engine for .NET web applications, designed to simplify and provide essential tools for developing web apps.</Description>
        <PackageId>TinyAppEngine.Tools</PackageId>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/AngeloDotNet/AppEngine</PackageProjectUrl>
        <PackageIcon>LibraryTools.png</PackageIcon>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.OpenApi" Version="10.0.1" />
        <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LibraryTools.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Nerdbank.GitVersioning" Version="3.10.91" />
    </ItemGroup>
</Project>
