using Microsoft.Extensions.Logging;

namespace AppEngine.Caching.Options;

/// <summary>
/// Represents the configuration options for controlling log levels of various FusionCache events.
/// </summary>
/// <remarks>Use this class to specify the log levels for different categories of FusionCache operations, such as
/// fail-safe activation, serialization errors, distributed cache timeouts and errors, and factory-related issues.
/// Adjusting these options allows fine-grained control over the verbosity and importance of log messages generated by
/// FusionCache.</remarks>
public class FusionCacheLoggingOptions
{
    /// <summary>
    /// Gets or sets the log level used when fail-safe activation occurs.
    /// </summary>
    /// <remarks>This property determines the minimum severity of log messages that are recorded during
    /// fail-safe activation scenarios. Adjust this value to control the verbosity of logs when the system enters a
    /// fail-safe state.</remarks>
    public LogLevel FailSafeActivationLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used for serialization error messages.
    /// </summary>
    public LogLevel SerializationErrorsLogLevel { get; set; } = LogLevel.Warning;

    /// <summary>
    /// Gets or sets the log level used for synthetic timeout events in the distributed cache.
    /// </summary>
    /// <remarks>Synthetic timeouts are generated when the distributed cache operation exceeds a configured
    /// threshold. Adjust this property to control the verbosity of logging for such events. This can help with
    /// diagnosing cache latency or availability issues.</remarks>
    public LogLevel DistributedCacheSyntheticTimeoutsLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used when logging distributed cache errors.
    /// </summary>
    /// <remarks>This property determines the minimum severity of distributed cache errors that will be
    /// logged. Adjust this value to control the verbosity of error logging for distributed cache operations.</remarks>
    public LogLevel DistributedCacheErrorsLogLevel { get; set; } = LogLevel.Error;

    /// <summary>
    /// Gets or sets the log level used for synthetic timeout events generated by the factory.
    /// </summary>
    public LogLevel FactorySyntheticTimeoutsLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used for recording factory error messages.
    /// </summary>
    public LogLevel FactoryErrorsLogLevel { get; set; } = LogLevel.Error;
}