name: Publish AppEngine Validations on BaGet
 
permissions:
  contents: read
  
on:
  push:
    branches: [ main ]
    paths: [ 'src/AppEngine.Validations/**' ]
  workflow_dispatch:
      
env:
  NET_VERSION: '10.x'
  PROJECT_NAME: src/AppEngine.Validations
  PROJECT_FILE: AppEngine.Validations.csproj
  RELEASE_NAME: AppEngine.Validations

jobs:
  build:
    name: Publish on GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'

    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #  
    #- name: Run unit tests
    #  run: dotnet test

    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.5
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}

    - name: Package
      run: dotnet pack -c Release -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'

    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.BAGET_API_KEY }} -s http://nuget.aepserver.it/v3/index.json --allow-insecure-connections --no-symbols --skip-duplicate
